<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LP0ER4S" failures="2" tests="9" name="com.adactin.testcases.LoginPageTest" time="39.237" errors="0" timestamp="30 May 2025 08:02:37 GMT" skipped="0">
  <testcase classname="com.adactin.testcases.LoginPageTest" name="verifyForgotPassword" time="2.820"/>
  <testcase classname="com.adactin.testcases.LoginPageTest" name="verifyFunctionalityForGooglePlayTest" time="4.857">
    <failure message="expected [https://play.google.com/store/apps/details?id=com.adactin.education.hotelbooking] but found [https://adactinhotelapp.com/index.php]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://play.google.com/store/apps/details?id=com.adactin.education.hotelbooking] but found [https://adactinhotelapp.com/index.php]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.adactin.testcases.LoginPageTest.verifyFunctionalityForGooglePlayTest(LoginPageTest.java:96)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyFunctionalityForGooglePlayTest -->
  <testcase classname="com.adactin.testcases.LoginPageTest" name="verifyFunctionalityForiOSTest" time="7.606">
    <failure message="expected [https://testflight.apple.com/join/Ai3nVPMD] but found [https://adactinhotelapp.com/index.php]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://testflight.apple.com/join/Ai3nVPMD] but found [https://adactinhotelapp.com/index.php]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.adactin.testcases.LoginPageTest.verifyFunctionalityForiOSTest(LoginPageTest.java:73)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyFunctionalityForiOSTest -->
  <testcase classname="com.adactin.testcases.LoginPageTest" name="verifyLogoTest" time="2.359"/>
  <testcase classname="com.adactin.testcases.LoginPageTest" name="verifyTitleTest" time="2.317"/>
  <testcase classname="com.adactin.testcases.LoginPageTest" name="verifyLoginFunctionality" time="4.927"/>
  <testcase classname="com.adactin.testcases.LoginPageTest" name="verifyLoginFunctionality" time="5.048"/>
  <testcase classname="com.adactin.testcases.LoginPageTest" name="verifyNewUserRegisterHereLink" time="3.305"/>
  <testcase classname="com.adactin.testcases.LoginPageTest" name="verifyLoginFunctionality" time="5.998"/>
</testsuite> <!-- com.adactin.testcases.LoginPageTest -->
